version: "3"

services:

  # kafka:
  #   image: spotify/kafka
  #   hostname: kafka
  #   environment:
  #     ADVERTISED_HOST: kafka
  #     ADVERTISED_PORT: 9092
  #   ports:
  #     - "9092:9092"
  #     - "2181:2181"

  GLProcessor:
    image: spireon/GLProcessor:latest
    environment:
      KAFKAHOST: "kafka.i.spireon.com"
      KAFKAPORT: "9092"  
      ORIGINTOPIC: "DeviceLocationChangeTopic" 
      DESTTOPIC: "DeviceLocationChangeTopicImpound"
      GROUPID: "ImpoundLotGroupId1337"
      DEBUG: "true"
